DEV: Adding Attenuators
pcdshub/lcls-twincat-pmps pull request #97
Opened 2021-09-08 17:51 UTC by ghalym

Just like the stoppers and the apertures, all the gas and solid attenuators are added as L_Attenuators and K_Attenuators

2021-09-08 18:01 UTC, klauer requested changes
Additional enums look fine, minus the one capitalization difference.

What is the .TcTLEO file extension here? I don't recall seeing that - and I think our pre-commit doesn't format those files by default at least.

2021-09-08 18:16 UTC, ghalym commented on lcls-twincat-pmps/PMPS/DUTs/InternalDUT/K_Attenuators.TcTLEO
> +	AT2k2 := 4, // RIX Solid Attenuator
I fixed it. And these are internal DUTs

2021-09-08 18:31 UTC, klauer approved these changes

2021-09-08 22:18 UTC, ghalym commented
@slacAWallace I made the new files with textlist support this way they are the same as the L_Stopper and K_stopper. Is there a specific reason for having them with textlist support?

2021-09-08 22:21 UTC, slacAWallace commented
Textlist support pertains to TC HMI display iirc. Not sure why it's important or enabled for any struct in this project. It may be an artifact of the HMI testing I was doing before using TcUnit.

2021-09-08 23:40 UTC, ghalym commented
I just removed all textlist support files. now they are all .TcDUT.

2021-09-08 23:46 UTC, klauer commented
Looks better to me, Maggie! Sorry for the extra work :)

2021-09-09 16:17 UTC, ZLLentz commented on lcls-twincat-pmps/PMPS/DUTs/InternalDUT/K_Stopper.TcDUT
> +    DEFAULT := PMPS_GVL.MAX_VETO_DEVICES // DO NOT USE FOR ANYTHING
Why is this here if we aren't supposed to use it?

2021-09-09 16:17 UTC, ZLLentz commented on lcls-twincat-pmps/PMPS/DUTs/InternalDUT/K_Stopper.TcDUT
> +    DEFAULT := PMPS_GVL.MAX_VETO_DEVICES // DO NOT USE FOR ANYTHING
Not important for this PR but just curious

2021-09-09 16:18 UTC, ZLLentz approved these changes

2021-09-09 16:25 UTC, merged